= Comparing Open Edition and SAP Edition
//TODO: Shift this topic one level higher to a more general overview of the DXP-Editions (when it is available)

Open Edition and SAP Edition are the two major product versions Neptune offers.
You can exchange artifacts from services that are used in both editions.

== Hosting
The SAP Edition uses ABAP Runtime ICF node as the runtime environment.
Each module has its own hosting methods.
//module=edition? If so, state it first, then explain different editions.
The SAP Edition is embedded within the SAP system and runs within the NetWeaver stack.

The Open Edition can be hosted on multiple platforms, for example, Oracle, AWS, or Azure.
The Open Edition is as easy to deploy as a docker container with Cloud Foundry.

== Services and components
Even though the Open Edition and the SAP Edition use different foundations, they share a number of similar components:

* _Launchpad_
* _App Designer_
* _Application building blocks_

The Open Edition comes with the following additional applications:

* _API Designer_
* _Script Editor_
* _Workflow_

The SAP Edition additionally offers API Factory, which makes it possible to automate the REST API generation of the following SAP artifacts:

* ABAP classes
* Function modules
* BAPIs
* ALV standard and custom reports


== Related topics
* xref:overview.adoc[]
* xref:overview-runtime.adoc[]
