=  Neptune DXP - Open Edition
//Fabian@Helle: Ich habe das Topic in mehrere Untertopics aufgesplittet, da es ziemlich lang war

////

- was genau will man aussagen? Als Einführung für Neueinsteiger?
- den UI5-Kram unten löschen? Oder ausgliedern?
-
////

//Helle: Ich bin insgesamt unzufrieden mit dem Topic. Es ist dazu da, Neueinsteigern bei der großen Auswahl an Services einen Überblick über die essenziellen Services zu verschaffen. Vorschlag: ersetzen durch Links zu den Service Doku und einer Beschreibung, wie die Services zusammenspielen? Die Inhalte, die hier zu den Services stehen, sollten in der Service Doku sein und nicht doppelt gepflegt werden, oder?

== Main components
//Helle: main services?
The Neptune DXP - Open Edition comprises the following main components:

* _Launchpad_
* _App Designer_
* _API Designer_
* _Workflow Engine_
* _Script Editor_
* _Application Building Blocks_
//Helle: not a service. Either name service (store) or don't mark as service
//* Adaptive Designer


=== Launchpad
The _Launchpad_ is a shell that hosts applications and provides these applications with services, such as navigation, personalization, and embedded support.

The _Launchpad_ serves as the single entry point to the DXP - Open Edition.
The _Launchpad_ consists of services, which are displayed depending on the role of the user.
Each service represents an application that a user can open.
Services can also show live data.
//Input needed: Information about different user roles needed.

The _Launchpad_ can host the following applications, which can run in parallel:

* Applications built in the Neptune DXP - Open Edition
* Applications built in the Neptune DXP - SAP Edition
* HTML5 web applications
* React applications
* SAP WebDynpro applications

=== App Designer
Use the _App Designer_ to create HTML5-based applications.

* Comprises over 200 Open UI5 framework components, ranging from basic elements to complex UI patterns. You can use the components out of the box or extend them to meet your requirements.
* Enables developers to quickly integrate APIs with no-code data binding.
* Supports manual or automatic language translation, using Google Translate. Your apps can automatically become multilingual.
* Comes with an integrated tool to see the API architecture of an app.
* Application building blocks speed up development by combining modular groups of elements.
* Offers a built-in version management. A UI sample library review enables the testing of interfaces and functionalities before implementation.

=== API Designer
With the _API Designer_, you create and configure reusable API definitions.

* Comes with a graphical user interface.
* Enables you to create API operations manually, import them from another Open Edition, or a Swagger 2.0 file.
//Input needed: "another Open Edition", from another version of the Open Edition, from another application built with the Open Edition, or...?
* Generates APIs for tables within the Neptune DX Platform.

=== Workflow
With workflows, you design, build, run, and manage workflows, starting from simple approvals to entire end-to-end processes that span across different organizations and applications.

Workflows facilitates and automates processes that require tasks to be performed by humans.
Each step of a transaction can be easily monitored.
Processes are completed from the beginning to the end.

=== Script Editor
With the _Script Editor_, you create server-side scripts that run in their own separate process on the server.
You can use APIs, tables, global scripts, and NPM modules.
Scripts are used to extend your instance beyond standard configurations.

With a script, you can automate processes, add functionalities, and integrate your instance with outside applications.

=== Application Building Blocks
Application building blocks are modular and reusable development components that vary in size from small code snippets and connectors to larger groups of user interface components and entire application templates.

Neptune provides a library of these application building blocks. You can download them in the store.

== Related topics
* xref:overview-runtime.adoc[]
* xref:overview-comparing.adoc[]
* xref:overview-openui5.adoc[]