=  Neptune DXP - Open Edition

== Main services and components

The Neptune DXP - Open Edition comprises the following main components:

* _Launchpad_
* _App Designer_
* _API Designer_
* _Script Editor_
* _Adaptive Designer_
* _Workflow_
* _Application Building Blocks_

//TODO: Insert image for process overview when available.

=== Launchpad
The _Launchpad_ is a shell that hosts applications and provides these applications with services, such as navigation, personalization, and embedded support.

The _Launchpad_ serves as the single entry point to the DXP - Open Edition.
The _Launchpad_ consists of services, which are displayed depending on the role of the user.
Each service represents an application that a user can open.
Services can also show live data.

The _Launchpad_ can host the following applications, which can run in parallel:

* Applications built in the Neptune DXP - Open Edition
* Applications built in the Neptune DXP - SAP Edition
* HTML5 web applications
* React applications
* SAP WebDynpro applications

For more information, see xref:cockpit-overview:launchpad-concept.adoc[Launchpad].

=== App Designer
Use the _App Designer_ to create HTML5-based applications.

* Comprises over 200 Open UI5 framework components, ranging from basic elements to complex UI patterns. You can use the components out of the box or extend them to meet your requirements.
* Enables developers to quickly integrate APIs with no-code data binding.
* Supports manual or automatic language translation, using Google Translate. Your apps can automatically become multilingual.
* Comes with an integrated tool to see the API architecture of an app.
* Application building blocks speed up development by combining modular groups of elements.
* Offers a built-in version management. A UI sample library review enables the testing of interfaces and functionalities before implementation.

For more information, see xref:cockpit-overview:app-designer.adoc[App Designer].

=== API Designer
With the _API Designer_, you create and configure reusable API definitions.

* Comes with a graphical user interface.
* Enables you to create API operations manually, import them from another Open Edition, or a Swagger 2.0 file.
* Generates APIs for tables within the Neptune DX Platform.

For more information, see xref:cockpit-overview:app-designer.adoc[API Designer].

=== Script Editor
With the _Script Editor_, you create server-side scripts that run in their own separate process on the server.
You can use APIs, tables, global scripts, and NPM modules.
Scripts are used to extend your instance beyond standard configurations.

With a script, you can automate processes, add functionalities, and integrate your instance with outside applications.

For more information, see xref:cockpit-overview:script-editor.adoc[Script Editor].

=== Workflow
With workflows, you design, build, run, and manage workflows, starting from simple approvals to entire end-to-end processes that span across different organizations and applications.

Workflows facilitates and automates processes that require tasks to be performed by humans.
Each step of a transaction can be easily monitored.
Processes are completed from the beginning to the end.

For more information, see xref:cockpit-overview:workflow.adoc[Workflow].

=== Application Building Blocks
Application building blocks are modular and reusable development components that vary in size from small code snippets and connectors to larger groups of user interface components and entire application templates.

Neptune provides a library of these application building blocks. You can download them in the store.

== Related topics
* xref:overview-runtime.adoc[]
* xref:overview-comparing.adoc[]
