= Adaptive templates

_Adaptive Designer_ comes with templates that represent the foundation and structure for different types of adaptive applications.
Because an adaptive application is based on an adaptive template, any changes you make to the adaptive template will reflect across all the adaptive applications that use it.

Adaptive templates are available with the application building block Adaptive Framework Templates in the _Store_.

You can differ two main types of adaptive templates that further group use-case-specific adaptive templates. To start creating your adaptive application, you can choose from the 5 following adaptive templates:

Adaptive application templates::
* Adaptive list
* Adaptive edit
* Analytic slice and dice

Adaptive tile templates::
* Adaptive tile chart
* Adaptive tile table

Use the adaptive application templates to build adaptive applications that you can start from their tiles in any launchpad where the adaptive applications are integrated.

Use the adaptive tile templates to create adaptive applications that run in adaptive tiles. Meaning, the adaptive application is directly running within the tile in any launchpad where the adaptive application is integrated.

== Related topics

* xref:adaptive-designer-adaptive-list.adoc[]
* xref:adaptive-designer-adaptive-edit.adoc[]
* xref:adaptive-designer-analytic-slice-and-dice.adoc[]
* xref:adaptive-designer-adaptive-tile-chart.adoc[]
* xref:adaptive-designer-adaptive-tile-table.adoc[]