= Adaptive templates

_Adaptive Designer_ comes with templates that represent the foundation and structure for different types of adaptive applications.
Because an adaptive application is based on an adaptive template, any changes you make to the adaptive template will reflect across all the adaptive applications that use it.
//TODO Leonie: What does it mean - change the template ? changes are most likely not done in the adaptive designer, correct? Bring section to introduction in overview, if essential.

//TODO Leonie: Explain that templates are available in an application building block in the Store. I doubt, it is the only way to use a template from this application building bock. Better check.

You can differ two main types of adaptive templates that further group use-case-specific adaptive templates. To start creating your adaptive application, you can choose from the 5 following adaptive templates:

Adaptive application templates::
* Adaptive list
* Adaptive edit
* Analytic slice and dice

Adaptive tile templates::
* Adaptive tile chart
* Adaptive tile table

//TODO Leonie: prepare slice and dice terminology; real Names to be used? add to terminology list;

//TODO Leonie: explain two main types with examples in the following

== Related topics
//TODO Leonie: fill with links to single 5 templates
