= Side navigation

The side navigation displays navigation structures with up to two levels that link to different pages. It consists of two parts:

Main navigation section:: Upper part of the side navigation containing links to pages in the user's current work context.
Utility section:: Lower part of the side navigation containing links to additional information, such as communities or documentation.

//TODO Leonie: Add SUI
//TODO Leonie: Create Partial for upper part

== Main navigation section
The _Adaptive Designer_ main navigation section links to the following pages:

Settings:: Configure your existing adaptive applications and adjust the following application settings:
* General application settings such as the ID, Name, Description, and the adaptive template.
* The data source
* The package

Designer:: Create and edit your adaptive application. This is the default page that opens when you start the _Adaptive Designer_.

Translation:: Translate your adaptive applications using the integrated translation API.

== Utility section
The _Adaptive Designer_ utility section links to the following additional information:

* Neptune community
* Open UI5 homepage

== Related topics

* xref:adaptive-designer-user-interface-at-a-glance.adoc[]
//TODO Leonie: fill with links to pages and overview

