= Configure an external API

In this topic, you learn how to configure an API to communicate with an API outside DXP - Open Edition.

//Prerequisites section missing. Should always be included, even if there are no prerequisites

== Procedure

NOTE: In this procedure we use sample data from the Star Wars universe.
You can exchange our data with your data in the procedure.

. In the Cockpit, go to *Connectivity* and click _API Designer_.
. In the _API Designer_, click *Add*.
+
*Result*: The API configuration dialog opens.
//Not a "dialog" according to our terminology list but a "window".
You start in the *General* tab.
+
. In *Type*, select *External*.
. In *API format*, Swagger 2.0 is preselected. You can select the newer version, Open API 3.0, here.
. Enter a *Name* for your external API.
. If you created a package or group for your APIs, applications, oData, and mock data before, you can select those from the *Group* or *Package* drop-down menu.
. Enter a short and meaningful *Description* to your API.
. In *Version*, enter a version number, for example, `1.0`, to keep track of changes to the API.
. In *Endpoint*, enter the URL of the external API, for example, `https://swapi.dev/api`.
+
IMPORTANT: Do not put a slash `/` at the end of the endpoint.

. In *Media Type*, define the type of content of your API. This is needed to communicate with your browser. By default, it is `application/json`.

. Activate any of the following options that fit your application:
+
--
include::partial$api-designer-create.adoc[tags=!*;external]
--

. Click *Save*.

*Result*: Your API is saved with the current settings and is added to the library in the _API Designer_.
The _API Designer_ adds an ID to your API and saves change dates.

== Results

* Your API is saved with the current settings and is added to the library in the _API Designer_.
* The _API Designer_ adds an ID to your API and saves change dates.
//Do not repeat step results here. Have them at one place only.

== Next steps

* xref:api-designer-external-api-add-operation.adoc[]

== Related topics

* xref:api-designer-external-api-create.adoc[]
* xref:api-designer.adoc[API Designer]