= Create an external API with the API Designer

In this topic, you learn how to create an API to communicate with an external API.

== Procedure

NOTE: In this procedure we use sample data from the Star Wars universe.
You can exchange our data with your data in the procedure.

. On the Cockpit, go to *Connectivity* and click _API Designer_.
. On the _API Designer_, click *Add*.
+
*Result*: The API configuration dialog opens.
You start in the *General* tab.
+
. In *Type*, select *External*.
. In *API format*, Swagger 2.0 is preselected. You can select the newer version, Open API 3.0, here.
. Enter a *Name* for your external API.
. If you created a package or group for your APIs, applications, oData, and mock data before, you can select those from the *Group* or *Package* drop-down menu.
. Enter a short and meaningful *Description* to your API.
. In *Version*, enter a version number, for example, `1.0`, to keep track of changes to the API.
. In *Endpoint*, enter the URL of the external API, for example, `https://swapi.dev/api`
. In *Media Type*, define the type of content of your api. This is needed to communicate with your browser. By default, it is `application/json`.

. Activate any of the following options that fit your application:
+
--
include::partial$api-designer-create.adoc[tags=!*;external]
--

. Click *Save*.

*Result*: Your API is saved with the current settings and is added to the library in the _API Designer_. The _API Designer_ adds an ID to your API and saves change dates.

== Results

* You have done XY.

== Related topics

* xref to topic
* xref to other topic