= Cockpit settings

You can open the cockpit settings by clicking on your username in the top right corner of the cockpit.

The available settings change depending on where you click on your username. There are two different views:

* One in the editors, for example, script editor or app designer
* One in all other places

You can change the following parameters:

== Cockpit

Theme:: Choose between `light` and `dark` mode. Changes are applied instantly.

Place Cockpit action buttons to the left:: Decide whether action buttons inside a service, for example, *add* or *start* are placed on the left side of your interface. By default, they are placed on the right side. This setting is not available in editors.

== Code Editor

Font size:: Set the font size. Available sizes are 12-18 px.

Font Familiy:: Only available in editors. Enter a font family.

Word wrap:: Decide if there is a scroll bar in editors when a code line gets too long or if it stops at a predefined line.

Font Ligature:: Check or uncheck to enable ligatures in text.

Show Folding Controls:: Check or uncheck to make the folding controls visible all the time or only when you do a mouse over.

Change Password:: Click to open a new dialog where you can set a new password.
