= Add a new launchpad

In this topic, you learn how to add a new tile.

== Prerequisites

* You have created at least one tile group in xref:tilegroup-add.adoc[].

== Procedure

. In the cockpit, go to *Administration* and click _Launchpad_.
+
*Result*: The list of existing launchpads open.
. Click *Add*.
+
*Result*: The settings of the launchpad open.

=== General tab

. In the *General* section, you define general information about your launchpad. *Name* refers to the name the launchpad artifact has in the system, while *Title* refers to the displayed name of the launchpad. A *Launchpad Application* can also be downloaded from the store.
. In the *Blackout* section, you can enable and provide messages to the user that are displayed when a chosen application cannot be reached.
. If you want only one app to be shown on your launchpad, you can choose thi app in the *Single App Launchpad* section. All other apps and tiles that might be selected will be hidden.
. In the *Login* section, you can define how users can login to your launchpad. You can create login scenarios in the _System Settings_.
. In the *UI5* section, you can choose the UI5 version your launchpad use. You can also choose a UI5 theme.
. In the *Settings* section, you can change general settings regarding the behaviour of your launchpad.
. In the *Main Menu Display* section, you can choose whether the menu is displayed in the header.
. In the *Active Apps Display* section, you can change the behaviour of apps you are currently working with.
. In the *Translation* section, you can choose in which languages user can see the launchpad.
. In the *External Users* section, you can choose if and to what conditions external users should be able to login to your launchpad.

=== Layout tab
You can configure the layout of your launchpad and see a live preview in the right pane when clicking *Save*.

Click *Add* to add a new layout style to your launchpad. You can have more than one layout style.

=== PWA tab
You can declare that your launchpad should serve as a progressive web app (PWA).

You can define the layout and display mode of your PWA, set an autolock when the app is not used, and enable the user to insert a pin code to restrict access to the app.

=== Header tab
You can define your header with javascript.

=== Tile group tab
In the *Tile group* tab, you can add child tile groups to your new tile group. The hierarchy is displayed on the launchpad.

. Click *Add* to open the dialog with the available tiles in the system.
. Click on a tile.
. Click *Select*.

You can drag and drop tile groups to change the order in which they are displayed on the launchpad.

=== Enhancement tab
You can enable multiple *Enhancements* for your launchpad and adapt them with custom Javascript code.

Click on an enhancement and toggle the *Activate* button to activate it.

=== Chatbot tab
You can enable a chatbot in your launchpad. This can either be a chatbot from IBM or SAP. You need to have an account there to connect to the chatbot.


== Related topics
* xref:launchpad-assign-objects.adoc[]
* xref:system-settings.adoc[]