= Add a new mobile client

In this topic, you learn how to add and configure a mobile client.

== Prerequisites

* You have created a launchpad in xref:cockpit-overview:launchpad.adoc[].
//@Fabian: Did you want to link to the Launchpad service?
//Either: You have xref:cockpit-overview:launchpad.adoc[created a launchpad].
//Or: You have created a launchpad with xref:launchpad-concept.adoc[Launchpad].

== Procedure

. In the Cockpit, go to *Administration* and click _Mobile Client_.
+
*Result*: The table of existing mobile clients open.
. Click *Add*.
+
*Result*: The settings of the mobile client open.
//@Fabian: we should talk about style and terminology here. Our list doesn't help, guidelines don't help. We differ when describing this page though it is always the same. I'll add it to agenda.
//Better: the mobile client configuration window opens?
=== General tab
//@Fabian: to me this has a concept/reference character rather than task. Maybe like this:
////
In the *General* section, you define general information about your mobile client.

. Enter a *Name* for your mobile client.
. In *Launchpad*, select the launchpad you want to create a mobile client for.

. In the *Author* section, provide information about the creator of the mobile client.
//Where do name, email etc. appear?
////

. In the *General* section, you define general information about your mobile client. *Name* refers to the name the mobile client artifact has in the system. You also set the *Launchpad* you want to use with your mobile client.
. In the *Author* section, you can provide information about the creator of the mobile client.

=== Security tab
. In the *Connection* section, you provide the server URL where the mobile client is hosted. You can also set an optional URL for resetting the password.
. In the *Autolock* section, you can set a period of time after which the system is automatically locked.
. In the *Pin Code* section, you can enable and configure login to the mobile client via pin code.
. In the *Biometric Authentication* section, you can enable authentication via fingerprint on a mobile device.

=== Device tab
. In the *Common* section, you provide the *App ID*. The *App ID* is structured as follows: `com.company.identifier`. An example is `com.neptune.testapp`.
. In the *Mobile Client Build* section, you can enable automatic updates for your app.
. In the *Platforms* section, you can define on which systems your app should run. If you choose `Windows 10`, you have to make some additional settings.
//TODO Neptune: What about special settings regarding Windows 11? Do they apply here as well?

=== Plugins tab
You can add Apache Cordova plugins to your mobile client. There are three ways to add plugins:

+Add:: An empty field opens. You can enter the name of the plugin.
Add from Library:: A new window with the list of available Cordova plugins in the system library opens. Choose the plugin you want and click *Select*.
Add from NPM:: A new window with the list of available Cordova plugins from the _NPM_ service opens. Choose the plugins you want and click *Select*.

You can click *Reset* to return to the default set of plugins that is recommended.

=== Custom Config tab
You can use the custom config editor to add XML code to edit your mobile application.

=== Push IOS & Push Android tabs
You can download configuration files from the firebase platform to push your mobile client to IOS or Android devices.

=== Media tab
You can enter an icon and a splashscreen for your mobile client that is derived from the media library.

=== Build tab
The build tab provides an overview of when this mobile client has been created.

* Click *Save* when you finished editing.

//@Fabian: This is quite a long topic. Having in mind what you said about the long topic with multiple sections that I had for App Designer, I suggest we do the same here and make workflow oriented rather than GUI oriented splits. We can establish a complex task with necessary steps and add optional steps.

== Results

* You have added and configured a mobile client.

== Related topics

* xref:mobile-client.adoc[Mobile Client]