= PDF Designer elements

With the _PDF Designer_ you can build your own PDF templates and documents.
The following topic shows an overview over all elements you can use to build your PDF template or document.

//Ask Hendrik, Explain: Why is there a small "o" before a component when it is in the components pane.

// Explain: The "PDF Document" element as top element
== Document components
//Use "::" instead of ";;" to stay consistent
Background;;
Shell for the background of your PDF template. You can insert every *Elements* component you want to display in the background of your PDF template.
//Ask Hendrik: Every element? You can have a table or a QR code as background?
Content;;
Shell for the content or body of your PDF template. You can insert every *Elements* component here.
//Dont't use "body" as term

Default Style;;
This element sets a default style for your PDF template. You can set, for example, fonts or colors for your entire PDF template.

Footer;;
Shell for the footer area of your PDF template. You can insert *Elements* components here,
for example, images or text.
You can also use formula as a text, for example, to show the
current page number and total page numbers:
+
[source, asciidoc]
----
{= `Page ${currentPage} of ${pageCount} `}
----

Header;;
Shell for the header area of your PDF template. See also Footer.

Settings;;
Element to configure the settings of your PDF document. You can set the size of your page or set passwords for your users to access and edit the document.

Styles;;
Element to define your custom styles and assign them to objects.
//TODO: can´t quite figure out what this element is for.

Watermark;;
Element to add a watermark to your PDF document. The watermark will appear on every page of your PDF document.

== Elements components

Canvas;;
Element to set the style of a specific section of your PDF template.

Columns;;
Element to divide a section of your PDF template into columns.

Image;;
Element to insert an image in your PDF template.

ListBulleted;;
Element to insert a list with bullet points into your PDF template.

ListNumbered;;
Element to insert a numbered list into your PDF template.

QR Code;;
Element to insert a QR Code into your PDF template.

Stack;;
This element...

Style;;
This element...

Table;;
Element to insert a table into your PDF template. You can insert *TableRow* elements to add more rows to your table.

TableRow;;
Element to add a new row to a table. Can be inserted in *Table* elements only.

Text;;
Element to insert a simple text block to your PDF template. You can also add this element to *Footer*, *Header*, *Watermark*,
*Columns*, *ListBulleted*, *ListNumbered* and *TableRow* elements.

== Related topics

* xref:pdf-designer-create-pdf.adoc[Create a new PDF template]
* xref:pdf-designer-edit-template.adoc[Edit a PDF template]
* xref:pdf-designer.adoc[PDF Designer]