= Configure the layout of your tile group

In this topic, you learn how to configure the layout of your tile group

== Prerequisites

* You have configured the general settings of your tile in xref:tile-add.adoc[].

== Procedure

. In the Cockpit, go to *Administration* and click _Tile Group_.
+
*Result*: The table of existing tile groups open.
. Click *Add*.
+
*Result*: The settings of the tile group open in the general tab.
. Go to the *Layout* tab.
. In the *Tiles Layout* section, you can configure the arrangement and general layout of tiles inside your tile group on the launchpad.
. In the *Tile Group Layout* section, you can configure the general layout of your tile group on the launchpad.
. In the *Tile Group Header* section, you can configure the layout of the tile group header.
. In the sections *Desktop*, *Tablet*, and *Mobile*, you can specify the layout of the tile group depending on the output medium.
. Click *Save*.

== Results

* You have configured the layout of your tile group.

== Related topics

* xref:tile-groups.adoc[]
* xref:tilegroup-task.adoc[]