= Add a new tile

In this topic, you learn how to add a new tile.

== Prerequisites

* There are no prerequisites.

== Procedure

. In the cockpit, go to *Administration* and click _Tile_.
+
*Result*: The list of existing tiles open.
. Click *Add*.
+
*Result*: The settings of the new tile opens.

=== General tab
. In the *General* section, you define the settings of the tile with regard to system internal processes. *Name* refers to the name the artifact has in the system.
. In the *Information* section, you provide general information about your tile. The information given here are displayed on the tile on the launchpad.

=== Layout tab
. In the *Layout* section, you define the general layout of your tile and how it is displayed on the launchpad, including background, width, and height.
. In the *Tile Icon/Image* section, you can provide an icon for your tile. Icons can also be appropriately sized images. Image or icon are derived from the media library.
. In the *Tile Background Image* section, you can choose and configure a background image for your tile.
. In the *Hide Tile On* section, you can decide whether your tile should not be displayed on a certain device.
. In the *Hide Launchpad Header On* section, you can decide whether the header of the launchpad should be hidden on a certain device.
. In the *Open Button* section, you define what text or which icon is displayed on the start button of the tile.

=== Action tab
. In the *Action* section, you decide what basic type your tile is. Default is application.
. In the *Remote System* section, you can configure a connection of your tile to another DXP - Open Edition or SAP Edition.
. In the *Application* section, you define what application your tile should run. Choose a stored artifact from the _App Designer_ and define start parameters.
. In the *How to open* section, you decide how your tile opens when started.

=== Sidepanel tab
In the *Sidepanel* section, you choose an application that is displayed on the sidepanel of your tile.

=== Navigation tab
. In the *Navigation* section, you can define semantic objects and actions that are performed on these objects. Semantic objects can be business entitys, for example, `customer` or `employee`.
. In the *Limit Browser Support* section, you can select specific browser that should be supported.

=== Documentation tab
. In the *Documentation* section, you can enable documentation for this tile that has been created in the _Documentation_ service.
. In the *Tile Help* section, you can enable and write documentation specifically for your tile.

=== Role tab
In the Role tab, you can specify that your tile should only be visible to user with a specific role.

=== Translation tab
In the translation tab, you can add a translation for the title, subtitle, description, status, and open button in a language of your choice.
You need to select the same language on the launchpad to see your translation.

=== Where-used
In the *Where-used* tab, you can see in which tile group the tile is used.

== Results

* You have added and configured a tile.

== Related topics
* xref:tiles.adoc[Tiles]
* xref:security-role.adoc[Role]
* xref:tile-groups.adoc[Tile Groups]
