= Add actions to your tile

In this topic, you learn how to add further actions to your tile.

== Prerequisites

* You have configured the general settings of your tile in xref:tile-add.adoc[].

== Procedure

. In the Cockpit, go to *Administration* and click _Tile_.
+
*Result*: The table of existing tiles open.
. Click *Add*.
+
*Result*: The settings of the tile open in the general tab.
. Go to the *Action* tab.
+
NOTE: The configuration options depend on the *Type* you choose.
. In the *Action* section, you decide what basic type the additional action on your tile should be.
Adaptive Framework:: Choose an adaptive framework that is stored in the system.
Application:: Choose a *Remote system* that you want to login. Choose an *Application* you want to run there.
Tile Group:: Enter a tile group that should be launched.
URL:: Enter a URL that should be started.
Web application:: Choose a *Remote system* that you want to login. Chosse a *Web Application* you want to run there.

. Click *Save*.

== Results

* You have configured further actions of your tile.

== Related topics

* xref:tile-task.adoc[]
* xref:tiles.adoc[Tiles]