= Workflow

A workflow provides an infrastructure for the setup, performance and monitoring of a defined sequence of tasks.
//performance is more often used in a different context in development. Alternative: ...infrastructure to set up, perform, and monitor a defined sequence...

With a workflow, you can design, build, run and manage workflows from simple approvals to complex processes that span across different organizations and applications.
It is a tool designed to facilitate and automate processes that require tasks to be performed by people.
Each step of a transaction can be easily monitored, and processes are completed from the beginning to the end.
//I don't understand the second half of this sentence. Why are they complicated?
An inbox application is used to receive notifications if it is a users turn to perform a step in the workflow.
//An inbox application notifies users/a user when it is their turn ...
In short, a workflow ensures that the right work is brought in the right sequence at the right time to the right people.


== Benefits of workflow
//marketing content?
There are the following benefits of using a workflow:

* Process improvement: Relevant information are sent directly to the user, according to the predefined steps in the workflow.
Nobody needs to approve a certain task for it to run.
* Process time is reduced by providing all necessary information so people can check their list of pending tasks and better plan their work.
* Using workflows, it is easy to manage task dependency and to send notifications in about pending actions.

== How does a workflow work?

The workflow is started either manually or by the system at runtime.
For the system to start a workflow, the workflow definition must contain a triggering event (for example the event "Address update by the employee").
When the event occurs, the relevant workflow is started automatically.
Tasks or Work items describe the activities involved and can refer to automatic executable methods (i.e. send an email to a supervisor), or they might need a user to execute them (i.e. the supervisor has to go and click on a button in his workplace to approve something).
//delete "in his workplace"?

Events are activities that trigger the workflow - one or several workflows at the time.
//...trigger one or several...
Once the workflow is triggered, the definition flowchart determines when and in what order work happens.
Work items are then received and executed in Planet 9 integrated inbox.
//Open Edition?
A work item is always assigned to one or more users.
Once the task is executed, the work item vanishes from the other users' inboxes.

* xref:workflow-overview.adoc[Overview]
* xref:workflow-definition.adoc[Definition]
** xref:workflow-start.adoc[]
* xref:workflow-task-action.adoc[Task Action]
* xref:workflow-approvers.adoc[Approvers]
* xref:workflow-substitutions.adoc[Substitutions]
