= Create a complex task

There are tasks that are too complex to be described in one topic. These tasks usually consist of a number of steps that must be completed in a specific order. These complex tasks are called *guide*.

The introductory topic of a guide is structured as follows.

[source, asciidoc]
----
= Title

In this guide, you learn how to...

This guide consists of the following steps:

* Task topic 1
* Task topic 2
* Task topic 3
* optional: Task topic 4
* (...)
----


== Optional tasks

Optional tasks in complex tasks are tasks that are not strictly necessary to fulfill the primary purpose of a topic.
However, optional tasks describe helpful additional capabilities that support that primary use.
For example, in order to create a tile, you do not need to know how to configure the layout, but it helps you a lot.

=== How to label optional topics

* In a complex task topic: Optional tasks are marked with "optional"
* In the table of content: Optional tasks are marked with "optional". All available topic shall appear in the table of content.
* In the concept topic of a service: Optional tasks are NOT marked with "optional"

Also see xref:links.adoc[].

