= Headings

== Levels
* Apart from the topic title (h1), we recommend that you use up to two subheadings (h2, h3) in a topic.
* You can use more subheadings if needed.
* Topics with three or more levels of headings tend to be too long.
Consider splitting up such a topic into two or more topics.
See also *Best practices* in xref:concept-topic.adoc[Concept topic].
* If you need more heading levels, you can also highlight a term in bold, followed by a colon or a full stop and write the heading starting with a capital letter.
Example::

*Heading 4*. Highlight a term in bold.

[IMPORTANT]
====
You assign the topic title (h1) only once.
If you refer to a topic by using an xref, the topic title appears as a link to the topic, unless otherwise stated.

Example:: overview.adoc[] appears as "Neptune DXP - Open Edition" in the table of content.
Compare code and preview.
However, you can provide an individual title in square brackets.
====

* Avoid hyphens in headings if you can.
In resized windows or mobile devices, hyphens can result in awkward line breaks.
* Do not use ampersands (&) or plus signs (+) in headings unless you are referring to the UI that contains them.
* Do not use italics in captions (the typographical convention for Cockpit services do not apply here)

== Capitalization
Use sentence style for all headings except for proper nouns.

Examples::
* Install the App Designer
* Design an application from scratch
* Getting started with the Tile Blackout
