= Links

Links from one topic to another are important to read more about a given topic that is explained in another place.
The user should be directed to content that is related to what he just read.
However, he should not be overwhelmed with unnecessary information that is only marginally related to what he is working on.

Also, the reader should not be interrupted in his reading of the current topic. Therefore, links should only be placed at some places in the topic.

The following rules for different topic types are used to decide which topics link where:

== Concept topics

Concept topics link to:

* All task topics that are related to that concept topic
* Parent or child concept topics
* All other topics whose content is necessary to understand the content of the topic

Where are links placed:

* In a *Related topics* section

== Links in task topics

Task topics link to:

* Service overview of the task (concept topic)
* First page of the task, if it consists of more than one step
* Next step
* Previous step

Task topics do NOT link to:

* Every next step in the sequence
* Every previous step in the sequence
* Other task topics related to the same service

Where are links placed:

* In a *Related topics* section
* In a *Next steps* section
* In the *Prerequisites* section

== Links in complex tasks

Complex tasks contain a concept topics, two or more mandatory task topics, and may contain optional task topics.
They link to each other in the following way:

[%header, frame=sides, frame=ends]
|===
|Topic type |Link to

|Service group overview
|Service concept

|Service concept topic
|Link to service group, Complex task, task, optional task

|Complex task
|Link to concept, task, optional task

|(Mandatory) Task
|

|In Next Steps
|Next mandatory task in sequence, all optional topics

|In Related Topics
|Complex task, Service concept

|Optional Task
|

|In Next Steps
|other optional topics

|In Related Topics
|Complex task, Service concept
|===
