= Connect the database

When you create your Azure Database for the PostgreSQL server, a default database named Postgres is created.
In this topic, you learn how to connect your database to DXP - Open Edition.

== Prerequisites

* xref:azure-create-database.adoc[Your Postgres database setup is complete].
* To connect to your database server, you need the following:
** Full server name
** Port number
** Admin login credentials
+
You can find the login information on the server *Overview* page.

== Procedure
. In the Cockpit, go to *Settings* and click _System Settings_.
. Click *Database* and edit the following:
//TODO: In the current version of the development portal is no "Database tab" https://gtmdemosystem.neptune-software.cloud/cockpit.html#settings-system. Has it moved somewhere else?
Username:: Type the username for the server administrator that you provided when you created the Azure Database for PostgreSQL Server.
Port:: Enter the port to use when you connect to the Azure Database for PostgreSQL server.
Database:: The default database name generated by the system for the first connection.
URI:: Enter the URL. Example: `postgres://myadmin:mypwd@mydemoserver.postgres.database.azure.com:5432/mydemoserver`
+
. Click *Save*.
. Restart the application.

== Result

* You have configured your database and connected it to DXP - Open Edition.

== Related topics

* xref:azure-further-information.adoc[Further readings on Azure]
