= Install  DXP - Open Edition into Oracle Cloud

In this topic, you learn how to install DXP - Open Edition into the Oracle Cloud instance of Neptune. The following guide explains the necessary steps for Linux.

== Prerequisites

* You have access to the Oracle Cloud instance of Neptune, see xref:oracle-cloud-check.adoc[].
* You have a valid SSH key.

== Procedure

. Open a console in the directory where you want to store the installation files.
. Connect to the Oracle instance via SSH by typing the following:
+
[source,asciidoc]
----
username@host:~$ ssh
----
. Enter your passphrase.
+
You are now connected to the system.
+
. Install DXP - Open Edition by typing the following:
+
[source,asciidoc]
----
wget "https://www.dropbox.com/s/s8dbl7ymjtzxly5/planet9-linux/planet9-linux" -O planet9-linux
----
The installation starts and reports back when finished.
+
. Make the installation file executable by typing the following:
+
[source,asciidoc]
----
chmod +x planet9-linux
----
. To start DXP - Open Edition, type the following:
+
[source,asciidoc]
----
./planet9-linux
----

== Results
* DXP - Open Edition is running on the Oracle loud.

== Next steps
IMPORTANT: As soon as you disconnect from your SSH session the instance stops because the parent that started it no longer exists.

Run DXP - Open Edition with a session manager like xref:oracle-cloud-tmux.adoc[tmux].